services:
  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      MONGO_URI: mongodb://mongo:27017/bill_nest
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
